### ISSUE TITLE
Support of compound parameters (with multiple values)

### ISSUE THREAD

**Issue by Self-Perfection** [kimmoli/valuelogger#12]
Some real word events produces several values for logging (e.g. systolic and diastolic pressures from blood pressure measurements).

Support of multivalues parameters would save tap count required to log such events.
Moreover, single events should be saved in single db record. Current approach of tapping "add" for different parameters to sys/dia pressure produces records with different timestamps, so it becomes not trivial to combine this values later for analysis with external tools.

**Comment by kimmoli** [comment]
Yes, i have recognized this issue. 
I use the app to record also these two values, and also car mileage/fuel consumption by entering fuel amount and driven kilometers to the app - these would also require a formula to display liters/100km (or mpg)
I have some plans, but nothing solid made yet - maybe possibility to link 2 (or more) parameters, so that they can be entered with same timestamp, e.g. after entering first, it opens the entry page for next parameter with same timestamp.

**Comment by kimmoli** [comment]
Somekind paired parameter support implemented.

**Comment by kimmoli** [comment]
In version 0.5.0 parameters can be paired. 
Adding value to first parameter, will follow adding the second parameter.
Both parameters will have same timestamp, but still saved in separate db records.

Partial solution.
